# Generated by Django 4.2.13 on 2024-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_goods_slug_alter_goods_category_alter_goods_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterModelTable(
            name='goods',
            table='product',
        ),
    ]
