# Generated by Django 4.2.13 on 2024-10-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_goods_discount_alter_goods_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='GoodsCategory',
            new_name='ProductsCategory',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'Категорию товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
    ]
