# Generated by Django 4.2.13 on 2024-10-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_goods_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'Категория продукта', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelTable(
            name='productscategory',
            table='product_category',
        ),
    ]
